import test from 'node:test';
import assert from 'node:assert/strict';
import { INSTALL_SUGGESTION_DISMISS_MS, detectInstallSuggestionPlatform, hasExportableProgress, installSuggestionDismissalActive, installSuggestionDismissKey } from '../src/install-suggestion.js';

test('install suggestion detection covers iPhone, desktop-UA iPad, Android, and Safari on Mac',()=>{
  assert.equal(detectInstallSuggestionPlatform({userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1',platform:'iPhone',vendor:'Apple Computer, Inc.',maxTouchPoints:5}),'ios');
  assert.equal(detectInstallSuggestionPlatform({userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 Version/18.0 Safari/605.1.15',platform:'MacIntel',vendor:'Apple Computer, Inc.',maxTouchPoints:5}),'ios');
  assert.equal(detectInstallSuggestionPlatform({userAgent:'Mozilla/5.0 (Linux; Android 15; SM-S938U) AppleWebKit/537.36 Chrome/140.0 Mobile Safari/537.36',platform:'Linux armv8l',vendor:'Google Inc.',maxTouchPoints:5}),'android');
  assert.equal(detectInstallSuggestionPlatform({userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Version/18.0 Safari/605.1.15',platform:'MacIntel',vendor:'Apple Computer, Inc.',maxTouchPoints:0}),'mac');
});
test('Chrome on iOS and iPadOS gets Safari handoff guidance',()=>{assert.equal(detectInstallSuggestionPlatform({userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 CriOS/140.0 Mobile/15E148 Safari/604.1',platform:'iPhone',vendor:'Apple Computer, Inc.',maxTouchPoints:5}),'ios-chrome');assert.equal(detectInstallSuggestionPlatform({userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 CriOS/140.0 Version/18.0 Mobile/15E148 Safari/604.1',platform:'MacIntel',vendor:'Apple Computer, Inc.',maxTouchPoints:5}),'ios-chrome');});
test('install suggestion detection excludes non-Safari Mac and desktop browsers',()=>{assert.equal(detectInstallSuggestionPlatform({userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126.0 Safari/537.36',platform:'MacIntel',vendor:'Google Inc.',maxTouchPoints:0}),null);assert.equal(detectInstallSuggestionPlatform({userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/140.0 Safari/537.36',platform:'Win32',vendor:'Google Inc.',maxTouchPoints:0}),null);});
test('platform-specific dismissals expire after thirty days',()=>{const now=1_800_000_000_000;assert.equal(installSuggestionDismissKey('android'),'swarm-web-android-install-dismissed-v1');assert.equal(installSuggestionDismissalActive(String(now-INSTALL_SUGGESTION_DISMISS_MS+1),now),true);assert.equal(installSuggestionDismissalActive(String(now-INSTALL_SUGGESTION_DISMISS_MS),now),false);assert.equal(installSuggestionDismissalActive(null,now),false);});
test('backup action eligibility requires actual game progress',()=>{assert.equal(hasExportableProgress(null,{version:1,scores:{},achievements:[]}),false);assert.equal(hasExportableProgress({version:1},{version:1,scores:{},achievements:[]}),true);assert.equal(hasExportableProgress(null,{version:1,scores:{mission:{score:10}},achievements:[]}),true);assert.equal(hasExportableProgress(null,{version:1,scores:{},achievements:['E1']}),true);});
