// Authors the curated 22x24 Swarm XL campaign and emits src/xl-levels.js.
import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { installDomParser } from '../tests/support/xml-dom.mjs';
installDomParser();
import { cellKey, findPath, parseLevel } from '../src/core.js';

const root=dirname(dirname(fileURLToPath(import.meta.url))),GRID={cols:22,rows:24};
const esc=value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const key=cell=>cellKey(...cell),unique=(...groups)=>{const seen=new Set(),out=[];for(const group of groups)for(const cell of group){const k=key(cell);if(!seen.has(k)){seen.add(k);out.push(cell);}}return out;};
const vertical=(q,r0,r1,gaps=[])=>Array.from({length:r1-r0+1},(_,i)=>[q,r0+i]).filter(([,r])=>!gaps.includes(r));
const horizontal=(r,q0,q1,gaps=[])=>Array.from({length:q1-q0+1},(_,i)=>[q0+i,r]).filter(([q])=>!gaps.includes(q));
const rect=(q0,q1,r0,r1)=>{const out=[];for(let q=q0;q<=q1;q++)for(let r=r0;r<=r1;r++)out.push([q,r]);return out;};
const ring=(q0,q1,r0,r1,gaps=[])=>unique(horizontal(r0,q0,q1),horizontal(r1,q0,q1),vertical(q0,r0+1,r1-1),vertical(q1,r0+1,r1-1)).filter(cell=>!gaps.includes(key(cell)));
const exit=(name,hex)=>({name,hex}),spawn=(name,hex,exitName)=>({name,hex,exit:exitName});
const creeps={
  easy:[['CHOMPER',26,60],['WIGGLE',28,58],['SPINNER',34,48],['STAR',40,42]],
  medium:[['CHOMPER',27,76],['WIGGLE',29,72],['SPINNER',35,62],['STAR',44,50],['CUBIC',31,82],['PULSAR',40,66]],
  hard:[['CHOMPER',28,88],['WIGGLE',30,82],['SPINNER',37,70],['STAR',47,58],['CUBIC',32,94],['PULSAR',42,76],['SWARM',35,44]]
};
const arsenal={starter:[['BLASTER',6]],easy:[['BLASTER',6],['LASER',10],['MISSILE',15],['THUMP',14]],full:[['BLASTER',6],['LASER',10],['MISSILE',15],['SHOCK',12],['THUMP',14]],thump:[['THUMP',14]]};
function makeWaves(spawns,apparent,maxStreams,types,baseCount){const waves=[];for(let wave=0;wave<apparent;wave++){const chains=Math.min(spawns.length,1+wave%maxStreams);for(let chain=0;chain<chains;chain++){const name=spawns[(wave+chain)%spawns.length].name,type=types[(wave+chain*2)%types.length],second=types[(wave+chain*2+1)%types.length],count=baseCount+Math.floor(wave/3);waves.push({spawn:name,concurrent:chain<chains-1,groups:wave%4===3?[{type,count:Math.max(3,count-2)},{type:second,count:Math.max(3,count-3)}]:[{type,count}]});}}return waves;}
function spec({file,id,name,difficulty,description,cash,lives,wealth,healthFactor,spawns,exits,blocked=[],pass=[],fast=[],heal=[],roster,towers,waveCount,streams,baseCount,placed=[]}){return {file,id,name,difficulty,description,cash,lives,wealth,healthFactor,spawns,exits,blocked:unique(blocked),pass:unique(pass,fast,heal),fast:unique(fast),heal:unique(heal),roster,towers,placed,waves:makeWaves(spawns,waveCount,streams,roster.map(c=>c[0]),baseCount)};}

const specs=[
  spec({file:'GAME_LEVEL_XL_E_0001.xml',id:200,name:'Beginner Swarm XL',difficulty:'Easy',description:'Two readable lanes introduce the XL camera, minimap, and paired exits.',cash:60,lives:15,wealth:.7,healthFactor:1.4,spawns:[spawn('s1',[0,5],'e1'),spawn('s2',[0,18],'e2')],exits:[exit('e1',[21,5]),exit('e2',[21,18])],blocked:vertical(10,3,20,[7,16]),roster:creeps.easy.slice(0,2),towers:arsenal.starter,waveCount:7,streams:2,baseCount:5}),
  spec({file:'GAME_LEVEL_XL_E_0002.xml',id:201,name:'Dual Channel XL',difficulty:'Easy',description:'Four approaches feed two fixed channels and teach simultaneous defense.',cash:66,lives:15,wealth:.7,healthFactor:1.45,spawns:[spawn('s1',[0,4],'e1'),spawn('s2',[0,19],'e2'),spawn('s3',[7,0],'e1'),spawn('s4',[14,23],'e2')],exits:[exit('e1',[21,4]),exit('e2',[21,19])],blocked:unique(rect(8,9,7,10),rect(12,13,13,16)),roster:creeps.easy.slice(0,3),towers:arsenal.easy,waveCount:8,streams:2,baseCount:5}),
  spec({file:'GAME_LEVEL_XL_E_0003.xml',id:202,name:'Down The Chute XL',difficulty:'Easy',description:'Fast and healing chutes stretch across a wider three-lane arena.',cash:72,lives:15,wealth:.7,healthFactor:1.5,spawns:[spawn('s1',[0,4],'e1'),spawn('s2',[0,12],'e1'),spawn('s3',[0,20],'e2')],exits:[exit('e1',[21,7]),exit('e2',[21,18])],blocked:unique(horizontal(8,4,17,[7,14]),horizontal(16,3,18,[6,15])),fast:horizontal(5,3,17),heal:horizontal(19,4,18),pass:vertical(11,9,15),roster:creeps.easy,towers:arsenal.easy,waveCount:10,streams:2,baseCount:6}),
  spec({file:'GAME_LEVEL_XL_E_0004.xml',id:203,name:'Ouroboros XL',difficulty:'Easy',description:'A broken outer ring turns a few dense swarms into a long looping pursuit.',cash:78,lives:12,wealth:.7,healthFactor:1.55,spawns:[spawn('s1',[0,6],'e1'),spawn('s2',[21,17],'e2')],exits:[exit('e1',[21,6]),exit('e2',[0,17])],blocked:ring(5,16,5,18,['5,10','5,11','16,12','16,13']),roster:creeps.easy,towers:arsenal.easy,waveCount:10,streams:2,baseCount:8}),
  spec({file:'GAME_LEVEL_XL_M_0001.xml',id:204,name:'Swarm-a-licious XL',difficulty:'Medium',description:'Four fronts orbit a charged center while mixed chains pressure both exits.',cash:90,lives:12,wealth:.65,healthFactor:1.7,spawns:[spawn('s1',[0,4],'e1'),spawn('s2',[0,19],'e2'),spawn('s3',[6,0],'e1'),spawn('s4',[15,23],'e2')],exits:[exit('e1',[21,6]),exit('e2',[21,17])],blocked:unique(rect(8,9,8,10),rect(12,13,13,15)),roster:creeps.medium.slice(0,5),towers:[...arsenal.full,['POP',20]],placed:[['POP',[11,12]]],waveCount:12,streams:3,baseCount:6}),
  spec({file:'GAME_LEVEL_XL_M_0002.xml',id:205,name:'Inward Spiral XL',difficulty:'Medium',description:'Six entrances spiral toward two interior drains and demand overlapping coverage.',cash:102,lives:12,wealth:.6,healthFactor:1.75,spawns:[spawn('s1',[0,3],'e1'),spawn('s2',[0,20],'e2'),spawn('s3',[5,0],'e1'),spawn('s4',[16,0],'e2'),spawn('s5',[6,23],'e1'),spawn('s6',[15,23],'e2')],exits:[exit('e1',[10,11]),exit('e2',[12,13])],blocked:unique(vertical(6,4,18,[8,15]),horizontal(6,7,17,[11]),vertical(17,6,19,[10,16]),horizontal(18,5,16,[10,13])),roster:creeps.medium,towers:arsenal.full,waveCount:13,streams:3,baseCount:6}),
  spec({file:'GAME_LEVEL_XL_M_0003.xml',id:206,name:'Nucleotide XL',difficulty:'Medium',description:'Mirrored terrain pairs twist three concurrent chains around a central backbone.',cash:96,lives:10,wealth:.65,healthFactor:1.8,spawns:[spawn('s1',[0,5],'e1'),spawn('s2',[0,18],'e2'),spawn('s3',[21,5],'e2'),spawn('s4',[21,18],'e1')],exits:[exit('e1',[9,23]),exit('e2',[13,0])],blocked:unique(vertical(10,3,20,[7,12,17]),vertical(12,3,20,[6,12,18])),fast:unique(horizontal(8,3,8),horizontal(15,14,19)),pass:unique(horizontal(15,3,8),horizontal(8,14,19)),roster:creeps.medium,towers:arsenal.full,waveCount:12,streams:3,baseCount:7}),
  spec({file:'GAME_LEVEL_XL_M_0004.xml',id:207,name:'Minefield XL',difficulty:'Medium',description:'Sparse islands leave six entrances open for large three-chain assaults.',cash:108,lives:15,wealth:.55,healthFactor:1.8,spawns:[spawn('s1',[0,3],'e1'),spawn('s2',[0,12],'e2'),spawn('s3',[0,20],'e3'),spawn('s4',[21,4],'e1'),spawn('s5',[21,11],'e2'),spawn('s6',[21,19],'e3')],exits:[exit('e1',[6,23]),exit('e2',[11,0]),exit('e3',[16,23])],blocked:unique(rect(5,6,6,7),rect(10,11,11,12),rect(15,16,16,17),rect(15,16,5,6),rect(5,6,16,17)),fast:[[8,8],[13,14]],heal:[[8,15],[13,7]],roster:creeps.medium,towers:[...arsenal.full,['POP',20]],placed:[['POP',[11,12]]],waveCount:12,streams:3,baseCount:7}),
  spec({file:'GAME_LEVEL_XL_H_0001.xml',id:208,name:'Middle Ground XL',difficulty:'Hard',description:'Three paired sectors share one middle ground while four chains arrive at once.',cash:120,lives:10,wealth:.6,healthFactor:1.95,spawns:[spawn('s1',[0,3],'e1'),spawn('s2',[0,12],'e2'),spawn('s3',[0,20],'e3'),spawn('s4',[21,3],'e1'),spawn('s5',[21,12],'e2'),spawn('s6',[21,20],'e3')],exits:[exit('e1',[10,0]),exit('e2',[11,23]),exit('e3',[16,0])],blocked:unique(horizontal(8,3,18,[6,11,16]),horizontal(16,3,18,[5,11,17])),pass:vertical(11,4,19),roster:creeps.hard,towers:arsenal.full,waveCount:14,streams:4,baseCount:7}),
  spec({file:'GAME_LEVEL_XL_H_0002.xml',id:209,name:'Lovely Flowers XL',difficulty:'Hard',description:'Eight petal entrances bloom around four paired exits and shifting terrain.',cash:132,lives:10,wealth:.55,healthFactor:2,spawns:[spawn('s1',[0,3],'e1'),spawn('s2',[0,20],'e2'),spawn('s3',[21,3],'e3'),spawn('s4',[21,20],'e4'),spawn('s5',[5,0],'e1'),spawn('s6',[16,0],'e3'),spawn('s7',[5,23],'e2'),spawn('s8',[16,23],'e4')],exits:[exit('e1',[8,8]),exit('e2',[8,16]),exit('e3',[14,8]),exit('e4',[14,16])],blocked:unique(ring(4,9,5,11,['6,5','9,8']),ring(13,18,5,11,['16,5','13,8']),ring(4,9,14,20,['6,20','9,17']),ring(13,18,14,20,['16,20','13,17'])),fast:[[11,6],[11,18]],heal:[[6,12],[16,12]],roster:creeps.hard,towers:arsenal.full,waveCount:14,streams:4,baseCount:8}),
  spec({file:'GAME_LEVEL_XL_H_0003.xml',id:210,name:'Thump This XL',difficulty:'Hard',description:'Eight fixed lanes and one tower class turn the whole XL grid into a rhythm puzzle.',cash:196,lives:10,wealth:.55,healthFactor:2,spawns:[spawn('s1',[0,3],'e1'),spawn('s2',[0,8],'e2'),spawn('s3',[0,15],'e3'),spawn('s4',[0,20],'e4'),spawn('s5',[21,3],'e5'),spawn('s6',[21,8],'e6'),spawn('s7',[21,15],'e7'),spawn('s8',[21,20],'e8')],exits:[exit('e1',[7,0]),exit('e2',[10,0]),exit('e3',[7,23]),exit('e4',[10,23]),exit('e5',[13,0]),exit('e6',[16,0]),exit('e7',[13,23]),exit('e8',[9,23])],blocked:unique(rect(5,6,6,17),rect(15,16,6,17),rect(10,11,9,14)),pass:unique(horizontal(5,2,19),horizontal(18,2,19)),roster:creeps.hard,towers:arsenal.thump,waveCount:12,streams:4,baseCount:8}),
  spec({file:'GAME_LEVEL_XL_H_0004.xml',id:211,name:'Looking Glass XL',difficulty:'Hard',description:'A mirrored six-lane finale reflects every mistake across four destinations.',cash:132,lives:6,wealth:.6,healthFactor:2.05,spawns:[spawn('s1',[0,4],'e1'),spawn('s2',[0,12],'e2'),spawn('s3',[0,19],'e3'),spawn('s4',[21,4],'e4'),spawn('s5',[21,12],'e2'),spawn('s6',[21,19],'e1')],exits:[exit('e1',[7,0]),exit('e2',[11,23]),exit('e3',[15,0]),exit('e4',[15,23])],blocked:unique(vertical(7,4,20,[8,16]),vertical(15,3,19,[7,15]),horizontal(11,8,14,[11])),pass:unique(vertical(10,4,9),vertical(12,15,20)),fast:unique(vertical(12,4,9),vertical(10,15,20)),heal:[[11,6],[11,18]],roster:creeps.hard,towers:arsenal.full,waveCount:16,streams:4,baseCount:8})
];

function xml(spec){const lines=['<?xml version="1.0"?>','<gameLevel>',`\t<info name="${esc(spec.name)}" id="${spec.id}" initCash="${spec.cash}" initLives="${spec.lives}" description="${esc(spec.description)}" />`,`<hexmap cols="${GRID.cols}" rows="${GRID.rows}">`];for(const e of spec.exits)lines.push(`\t<exithex name="${e.name}" hex="${key(e.hex)}"/>`);for(const s of spec.spawns)lines.push(`\t<spawnhex name="${s.name}" hex="${key(s.hex)}" exit="${s.exit}"/>`);for(const cell of spec.blocked)lines.push(`\t<specialhex type="blocked" hex="${key(cell)}"/>`);for(const cell of spec.pass.filter(cell=>!spec.fast.some(v=>key(v)===key(cell))&&!spec.heal.some(v=>key(v)===key(cell))))lines.push(`\t<specialhex type="pass" hex="${key(cell)}"/>`);for(const cell of spec.fast)lines.push(`\t<specialhex type="fastpass" hex="${key(cell)}"/>`);for(const cell of spec.heal)lines.push(`\t<specialhex type="healpass" hex="${key(cell)}"/>`);for(const [type,cell] of spec.placed)lines.push(`\t<placetower type="${type}" hex="${key(cell)}"/>`);lines.push('</hexmap>',`\t<creeps waveHealthFactor="${spec.healthFactor}" waveSpeedFactor="1.02" waveWealthFactor="${spec.wealth}">`);for(const [type,speed,health] of spec.roster)lines.push(`\t\t<creep type="${type}" speed="${speed}" health="${health}" />`);lines.push('\t</creeps>','\t<creepWaves delayBetweenWaves="16" delayBetweenSpawns="0.65">');for(const wave of spec.waves){lines.push(`\t\t<wave spawnHex="${wave.spawn}"${wave.concurrent?' concurrent="true"':''}>`);for(const group of wave.groups)lines.push(`\t\t\t<spawn type="${group.type}" count="${group.count}"/>`);lines.push('\t\t</wave>');}lines.push('\t</creepWaves>','\t<towers>');for(const [type,cost] of spec.towers)lines.push(`\t\t<tower type="${type}" cost="${cost}"/>`);lines.push('\t</towers>','</gameLevel>');return lines.join('\n');}

function validate(spec,source){const level=parseLevel(source,`XL/${spec.file}`,spec.difficulty,'xl'),problems=[];for(const s of level.spawns){const route=findPath(s.cell,s.exit,level.blocked,level.grid);if(!route||route.length<8)problems.push(`invalid route ${s.name}`);}const spawnNames=new Set(level.spawns.map(s=>s.name)),types=new Set(Object.keys(level.creeps));for(const wave of level.waves){if(!spawnNames.has(wave.spawnName))problems.push(`unknown spawn ${wave.spawnName}`);for(const group of wave.groups)if(!types.has(group.type))problems.push(`unknown creep ${group.type}`);}const cheapest=Math.min(...level.towers.filter(t=>t.type!=='POP').map(t=>t.cost)),floor={Easy:8,Medium:11,Hard:14}[level.difficulty];if(level.cash<cheapest*floor)problems.push('opening cash below XL floor');return {level,problems};}

async function main(){const entries=[];let ok=true;for(const item of specs){const source=xml(item),{level,problems}=validate(item,source);if(problems.length){ok=false;console.error(`✗ ${item.name}: ${problems.join(', ')}`);}else console.log(`✓ ${item.name.padEnd(24)} ${level.difficulty} routes=${level.spawns.map(s=>findPath(s.cell,s.exit,level.blocked,level.grid).length).join('/')} waves=${level.apparentWaves}`);entries.push({sourceName:`XL/${item.file}`,xml:source});}if(!ok)throw new Error('XL validation failed; output not written.');const header='// GENERATED by scripts/build-xl-pack.mjs — do not edit by hand.\n// Curated 22x24 Swarm XL expansion.\n';await writeFile(join(root,'src','xl-levels.js'),`${header}export const entries = [\n${entries.map(entry=>'  '+JSON.stringify(entry)).join(',\n')}\n];\n`);console.log(`Wrote src/xl-levels.js — ${entries.length} missions.`);}
main().catch(error=>{console.error(error);process.exit(1);});
