// One-time (re)generation of the in-repo bundled game data.
//
// Reads the user's legally-obtained original archives and emits two committed
// ES modules that let the engine boot standalone:
//   src/bundled-levels.js   — raw level XML for all missions (parsed in-browser)
//   src/bundled-strings.js  — localized UI string tables (en/de/es/fr/it)
//
// Only these two data buckets are shipped; all art and audio are procedural.
// Reuses the exact browser code paths (openZip, loadArchiveStrings) and the
// shared discovery in src/level-index.js so bundled data matches the archive
// import byte-for-byte.
//
// Usage:
//   node scripts/extract-data.mjs [sourceDir]
//   GEO_ARCHIVE_DIR=/path/to/archives node scripts/extract-data.mjs
// sourceDir must contain the .xap (required) and optionally the .ipa (adds the
// Level Pack 1 + Original geoDefense missions). Defaults to <repo>/archive.

import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { openZip } from '../src/zip.js';
import { loadArchiveStrings } from '../src/resources.js';
import { classifyName } from '../src/level-index.js';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const LANGS = ['en', 'de', 'es', 'fr', 'it'];

async function resolveSourceDir() {
  const candidates = [process.argv[2], process.env.GEO_ARCHIVE_DIR, join(root, 'archive')].filter(Boolean);
  for (const dir of candidates) {
    try {
      const files = await readdir(dir);
      if (files.some(f => /\.(xap|ipa|zip)$/i.test(f))) return dir;
    } catch { /* candidate does not exist — try the next */ }
  }
  return null;
}

async function openArchive(path) {
  const data = await readFile(path);
  return openZip({ arrayBuffer: async () => data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) });
}

function moduleHeader(cmd) {
  return `// GENERATED by scripts/extract-data.mjs — do not edit by hand.\n// Regenerate with: ${cmd}\n`;
}

async function main() {
  const sourceDir = await resolveSourceDir();
  if (!sourceDir) {
    console.log('No game archives found. Place your original .xap (and optional .ipa) in');
    console.log(`  ${join(root, 'archive')}`);
    console.log('or run: node scripts/extract-data.mjs <dir-containing-archives>');
    console.log('Skipping extraction (this is non-fatal).');
    return;
  }

  const names = (await readdir(sourceDir)).filter(f => /\.(xap|ipa|zip)$/i.test(f)).sort();
  console.log(`Reading ${names.length} archive(s) from ${sourceDir}`);
  const archives = await Promise.all(names.map(n => openArchive(join(sourceDir, n))));

  // --- Levels: collect every classifiable XML across all archives, dedupe by path. ---
  const entryMap = new Map();
  for (const archive of archives) {
    for (const name of archive.names) {
      if (classifyName(name) && !entryMap.has(name)) {
        entryMap.set(name, { sourceName: name, xml: await archive.text(name) });
      }
    }
  }
  const entries = [...entryMap.values()].sort((a, b) => a.sourceName.localeCompare(b.sourceName));
  const counts = { base: 0, lp: 0, classic: 0 };
  for (const e of entries) counts[classifyName(e.sourceName)]++;
  console.log(`Levels: ${entries.length} (base ${counts.base}, LP ${counts.lp}, classic ${counts.classic})`);
  if (counts.base !== 30) throw new Error(`Expected 30 base missions, found ${counts.base}. Is the Windows Phone .xap present and intact?`);
  if (counts.lp !== 5 || counts.classic !== 34) console.warn(`Note: LP1/classic counts differ from the archived 5/34 — the iOS .ipa may be missing.`);

  // --- Strings: use the archive that carries the managed .dll resources. ---
  const stringArchive = archives.find(a => a.has('geoLib.dll'));
  if (!stringArchive) throw new Error('No archive contains geoLib.dll — cannot extract localized strings.');
  const strings = {};
  for (const lang of LANGS) strings[lang] = sortKeys(await loadArchiveStrings(stringArchive, lang));
  console.log(`Strings: ${LANGS.map(l => `${l}=${Object.keys(strings[l]).length}`).join(', ')}`);

  // --- Emit the two committed modules. ---
  const cmd = 'node scripts/extract-data.mjs';
  const levelsBody = entries.map(e => '  ' + JSON.stringify(e)).join(',\n');
  await writeFile(join(root, 'src', 'bundled-levels.js'), `${moduleHeader(cmd)}export const entries = [\n${levelsBody}\n];\n`);
  await writeFile(join(root, 'src', 'bundled-strings.js'), `${moduleHeader(cmd)}export const strings = ${JSON.stringify(strings, null, 2)};\n`);
  console.log('Wrote src/bundled-levels.js and src/bundled-strings.js');
}

function sortKeys(obj) {
  return Object.fromEntries(Object.keys(obj).sort().map(k => [k, obj[k]]));
}

main().catch(err => { console.error(err); process.exit(1); });
