import { AudioBank } from './audio.js';
import { openZip } from './zip.js';
import { parseLevel, upgradeCost } from './core.js';
import { Game } from './game.js';
import { ACHIEVEMENTS, ProfileStore } from './profile.js';
import { loadArchiveStrings } from './resources.js';

const $=id=>document.getElementById(id),SAVE_KEY='swarm-web-save-v1',OPTIONS_KEY='swarm-web-options-v1';
let archive,levels=[],assets={},strings={},game,audioBank,currentDifficulty='Easy',options=readOptions(),gameOverUnlockTimer=0;
let profile;try{profile=new ProfileStore(localStorage);}catch{profile=new ProfileStore(null);}
const screens=[$('loader'),$('mainMenuScreen'),$('levelScreen'),$('gameScreen')];

function show(screen){screens.forEach(s=>s.hidden=s!==screen);}
function setStatus(text,error=false){$('loadStatus').textContent=text;$('loadStatus').style.color=error?'#ff7584':'';}
function t(key,fallback){return strings[key]??fallback;}
function readOptions(){const defaults={sound:true,healthBars:true,hardcore:true,placeAboveFinger:true};try{return {...defaults,...JSON.parse(localStorage.getItem(OPTIONS_KEY))};}catch{return defaults;}}
function saveOptions(){try{localStorage.setItem(OPTIONS_KEY,JSON.stringify(options));}catch{}if(audioBank)audioBank.enabled=options.sound;}
function readSave(){try{const save=JSON.parse(localStorage.getItem(SAVE_KEY));return save?.version===1&&save.state?.version===1?save:null;}catch{return null;}}
function storeSave(level,state){try{localStorage.setItem(SAVE_KEY,JSON.stringify({version:1,level:level.sourceName,state}));}catch{}}
function clearSave(){try{localStorage.removeItem(SAVE_KEY);}catch{}}
async function loadImage(name){if(!archive.has(name))return null;const url=await archive.imageUrl(name),img=new Image();img.src=url;img.objectUrl=url;await img.decode();return img;}
function disposeAssets(){const visit=value=>{if(value?.objectUrl)URL.revokeObjectURL(value.objectUrl);else if(value&&typeof value==='object')Object.values(value).forEach(visit);};visit(assets);assets={};}
function artBackground(img,shade='.34'){return img?`linear-gradient(rgba(0,4,15,${shade}),rgba(0,4,15,${shade})),url("${img.objectUrl}")`:'';}

$('archiveInput').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;try{setStatus(`Reading ${files.length} archive${files.length===1?'':'s'} locally…`);const opened=await Promise.all(files.map(openZip));archive=opened.find(z=>z.names.some(n=>/^Content\/MainLevels\/GAME_LEVEL_[EMH]_\d+\.xml$/i.test(n)));if(!archive)throw new Error('Include the original Windows Phone .xap.');const audioArchive=opened.find(z=>z.names.some(n=>n.toLowerCase().endsWith('/blastershot.wav')));audioBank?.dispose();audioBank=await AudioBank.fromArchive(audioArchive);if(audioBank)audioBank.enabled=options.sound;const names=archive.names.filter(n=>/^Content\/MainLevels\/GAME_LEVEL_[EMH]_\d+\.xml$/i.test(n));const baseLevels=(await Promise.all(names.map(async n=>parseLevel(await archive.text(n),n)))).sort((a,b)=>a.id-b.id);const lpEntries=opened.flatMap(z=>z.names.filter(n=>/(^|\/)GAME_LEVEL_LP\d+_[EMH]_\d+\.xml$/i.test(n)).map(name=>({zip:z,name})));const lpRank=n=>{const m=n.match(/_LP\d+_([EMH])_(\d+)/i);return m?{E:0,M:1,H:2}[m[1].toUpperCase()]*1000+Number(m[2]):9999;};const lpLevels=(await Promise.all(lpEntries.map(async e=>parseLevel(await e.zip.text(e.name),e.name,'Bonus')))).sort((a,b)=>lpRank(a.sourceName)-lpRank(b.sourceName));levels=[...baseLevels,...lpLevels];setStatus(`Loaded ${baseLevels.length} missions${lpLevels.length?` and ${lpLevels.length} bonus`:''}. Preparing original presentation…`);disposeAssets();const loaded=await Promise.all(['Content/BackdropP1.png','Content/Honeycomb.png','Content/Towers.png','Content/Creeps.png','Content/Shots.png','Content/MainMenu.png','Content/LevelSelect.png','Content/PreGame.png','Content/Buttons.png','Content/BuildBar.png','Content/TowerBar.png','Content/ScoreBar.png','Content/TouchIndicators.png','Content/Credits.png',...Array.from({length:9},(_,i)=>`Content/Tutorials/t${i+1}.png`)].map(loadImage));const [backdrop,honeycomb,towers,creeps,shots,mainMenu,levelSelect,preGame,buttons,buildBar,towerBar,scoreBar,touchIndicators,credits,...tutorials]=loaded;assets={backdrop,honeycomb,towers,creeps,shots,mainMenu,levelSelect,preGame,buttons,buildBar,towerBar,scoreBar,touchIndicators,credits,tutorials:Object.fromEntries(tutorials.map((img,i)=>[`t${i+1}`,img]))};$('mainMenuScreen').style.backgroundImage=artBackground(mainMenu,'.12');$('levelScreen').style.backgroundImage=artBackground(levelSelect,'.68');$('changeArchive').hidden=false;showMainMenu();}catch(err){console.error(err);setStatus(err.message,true);}});

async function showMainMenu(){game?.destroy();game=null;if(archive&&!Object.keys(strings).length){strings=await loadArchiveStrings(archive);assets.strings=strings;localizeMenu();}audioBank?.play('menu');$('menuDialog').hidden=true;const save=readSave(),savedLevel=save&&levels.find(l=>l.sourceName===save.level);$('continueGame').hidden=!savedLevel;if(savedLevel)$('continueGame').onclick=()=>startLevel(savedLevel,save.state);$('menuBonus').hidden=!levels.some(l=>l.difficulty==='Bonus');show($('mainMenuScreen'));}
function localizeMenu(){$('continueGame').textContent=t('ContinueSaved','Continue saved mission');$('menuEasy').textContent=t('EasyLevels','Easy levels');$('menuMedium').textContent=t('MediumLevels','Medium levels');$('menuHard').textContent=t('HardLevels','Hard levels');$('menuLeaderboards').textContent=t('Leaderboards','Leaderboards');$('menuAchievements').textContent=t('Achievements','Achievements');$('menuOptions').textContent=t('Options','Options');$('closeMenuDialog').textContent=t('Back','Back');$('backToMenu').textContent=`← ${t('MainMenu','Main menu')}`;$('levelScreen').querySelector('.section-heading h2').textContent=t('SelectLevel','Select level');}
function enterDifficulty(difficulty){currentDifficulty=difficulty;renderLevels();audioBank?.play('menu');show($('levelScreen'));}
$('menuEasy').onclick=()=>enterDifficulty('Easy');$('menuMedium').onclick=()=>enterDifficulty('Medium');$('menuHard').onclick=()=>enterDifficulty('Hard');$('menuBonus').onclick=()=>enterDifficulty('Bonus');$('backToMenu').onclick=showMainMenu;

function openMenuDialog(title){$('menuDialogTitle').textContent=title;$('menuDialogBody').replaceChildren();$('menuDialog').hidden=false;audioBank?.play('menu');return $('menuDialogBody');}
$('closeMenuDialog').onclick=()=>{$('menuDialog').hidden=true;audioBank?.play('menu');};
$('menuOptions').onclick=()=>{const body=openMenuDialog(t('Options','Options')),labels={sound:options.sound?t('SoundOn','Sound on'):t('SoundOff','Sound off'),placeAboveFinger:options.placeAboveFinger?t('PlaceAboveTouch','Place above touch'):t('PlaceAtTouch','Place at touch'),healthBars:options.healthBars?t('CreepHealthVisible','Creep health visible'):t('CreephealthHidden','Creep health hidden'),hardcore:options.hardcore?t('HardcoreMode','Hardcore mode'):t('NoviceMode','Novice mode')};for(const key of Object.keys(labels)){const row=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=options[key];input.onchange=()=>{options[key]=input.checked;saveOptions();$('menuOptions').onclick();};row.append(labels[key],input);body.append(row);}const aboutBtn=document.createElement('button');aboutBtn.id='menuAbout';aboutBtn.className='action';aboutBtn.textContent=t('About','About');aboutBtn.style.marginTop='18px';aboutBtn.onclick=showAbout;body.append(aboutBtn);const about=document.createElement('p');about.textContent='Critical Thought Games, LLC · Browser preservation engine';about.style.marginTop='16px';body.append(about);};
function showAbout(){if(!assets.credits)return;$('aboutImage').src=assets.credits.src;$('aboutOverlay').hidden=false;audioBank?.play('menu');}
$('aboutOverlay').onclick=()=>{$('aboutOverlay').hidden=true;audioBank?.play('menu');};
$('menuLeaderboards').onclick=()=>{const body=openMenuDialog(t('Leaderboards','Leaderboards')),list=document.createElement('div');list.className='profile-list';const rows=profile.leaderboard();if(!rows.length)list.textContent='No completed missions yet.';for(const score of rows){const row=document.createElement('div');row.className='profile-row';const name=document.createElement('span'),value=document.createElement('strong');name.textContent=score.name;value.textContent=score.score.toLocaleString();row.append(name,value);list.append(row);}body.append(list);};
$('menuAchievements').onclick=()=>{const body=openMenuDialog(t('Achievements','Achievements')),list=document.createElement('div'),earned=new Set(profile.data.achievements);list.className='profile-list';for(const [code,label] of Object.entries(ACHIEVEMENTS)){const row=document.createElement('div');row.className='profile-row'+(earned.has(code)?'':' locked');const name=document.createElement('span'),state=document.createElement('strong');name.textContent=label;state.textContent=earned.has(code)?'UNLOCKED':'LOCKED';row.append(name,state);list.append(row);}body.append(list);};

$('changeArchive').onclick=()=>{game?.destroy();game=null;audioBank?.dispose();audioBank=null;strings={};disposeAssets();$('archiveInput').value='';setStatus('');show($('loader'));};
function levelBadgeRow(level){const high=profile.highScore(level);return level.endless?(high?324:260):(high?(high.livesLost===0?452:388):null);}
function makeBadge(sy){const c=document.createElement('canvas');c.width=58;c.height=56;c.className='level-badge';if(assets.buttons){const cx=c.getContext('2d');cx.globalCompositeOperation='lighter';cx.drawImage(assets.buttons,414,sy,58,56,0,0,58,56);}return c;}
function renderLevels(){const difficulties=['Easy','Medium','Hard',...(levels.some(l=>l.difficulty==='Bonus')?['Bonus']:[])];$('difficultyTabs').replaceChildren(...difficulties.map(d=>{const b=document.createElement('button');b.textContent=t(`${d}Levels`,d);b.className=d===currentDifficulty?'active':'';b.onclick=()=>{currentDifficulty=d;renderLevels();};return b;}));const cards=levels.filter(l=>l.difficulty===currentDifficulty).map((level,index)=>{const b=document.createElement('button'),high=profile.highScore(level);b.className='level-card';b.innerHTML=`<span class="level-number">MISSION ${String(index+1).padStart(2,'0')}</span><h3></h3><p></p><small></small>`;b.querySelector('h3').textContent=level.name;b.querySelector('p').textContent=level.description;b.querySelector('small').textContent=high?`${t('YourHighScore','High score')} ${high.score.toLocaleString()}`:'';const badge=levelBadgeRow(level);if(badge!=null)b.append(makeBadge(badge));b.onclick=()=>startLevel(level);return b;});$('levelGrid').replaceChildren(...cards);}

function startLevel(level,savedState=null){game?.destroy();clearTimeout(gameOverUnlockTimer);if(!savedState)clearSave();$('gameScreen').classList.remove('pregame-open','desktop-panel-open');$('toggleDesktopPanel').setAttribute('aria-expanded','false');$('toggleDesktopPanel').textContent='Desktop controls';$('gameOverlay').classList.remove('native-pregame','native-runtime');$('gameOverlay').onclick=null;show($('gameScreen'));audioBank?.play('menu');$('difficultyLabel').textContent=level.difficulty;$('levelName').textContent=level.name;$('levelDescription').textContent=level.description;$('gameOverlay').hidden=true;$('tutorialOverlay').hidden=true;$('pauseGame').textContent='Pause';$('backToLevels').textContent='← Missions';$('multiplier').textContent='×1';const buttons=level.towers.filter(t=>t.type!=='POP').map(t=>makeTowerButton(t));$('towerButtons').replaceChildren(...buttons);
  const updateSelection=t=>{buttons.forEach(v=>v.classList.remove('selected'));$('upgradeTower').disabled=!t||t.level>=7||t.upgradeRemaining>0;$('upgradeTower').textContent=t&&t.level<7?(t.upgradeRemaining>0?`Upgrading · ${Math.ceil(t.upgradeRemaining)}s`:`Upgrade · ${upgradeCost(t.cost,t.level)} credits`):'Upgrade selected tower';$('sellTower').disabled=!t;$('sellTower').textContent=t?(t.type==='POP'?'Detonate Vortex':`Sell · ${Math.floor(t.value/2)} credits`):'Sell selected tower';$('linkTower').disabled=!t||(!['BLASTER','LASER','MISSILE'].includes(t.type)&&!(t.type==='POP'&&t.level===7));$('laserLock').disabled=!t||t.type!=='LASER'||t.level<3;$('laserLock').textContent=t?.lockedHeading?'Restore Laser tracking':'Lock Laser heading';};
  game=new Game($('game'),level,assets,{stats:s=>{$('cash').textContent=s.cash;$('lives').textContent=s.lives;$('wave').textContent=`${s.wave}/${s.total}`;$('score').textContent=s.score;$('multiplier').textContent=`×${s.multiplier}`;$('startWave').disabled=s.complete||s.waiting;$('startWave').textContent=s.complete?'All waves launched':s.waiting?'Spawning current swarm':`Launch next wave · ${Math.ceil(s.nextWave)}s`;},message:t=>$('gameMessage').textContent=t,selection:updateSelection,sound:key=>audioBank?.play(key),save:state=>storeSave(level,state),pause:p=>showPauseMenu(level,p),end:(won,score,result)=>showGameOver(level,won,score,result)},savedState,options);updateSelection(null);showPreGame(level,savedState);
  function makeTowerButton(tower){const b=document.createElement('button');let down=null,dragged=false,suppress=false;b.className='tower-button';const name=t(`${tower.type[0]+tower.type.slice(1).toLowerCase()}TowerName`,tower.type);b.innerHTML='<span class="tower-dot"></span>';b.append(`${name} · ${tower.cost}`);b.style.color=towerColor(tower.type);b.onpointerdown=e=>{if(e.button!==0)return;down={x:e.clientX,y:e.clientY};dragged=false;b.setPointerCapture?.(e.pointerId);};b.onpointermove=e=>{if(!down)return;if(!dragged&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)dragged=true;if(dragged)game.setBuildPreview(tower.type,e.clientX,e.clientY);};b.onpointerup=()=>{if(dragged){game.commitBuildPreview();suppress=true;}down=null;dragged=false;};b.onpointercancel=()=>{down=null;dragged=false;game.cancelBuildPreview();};b.onclick=()=>{if(suppress){suppress=false;return;}game.selectType(tower.type);buttons.forEach(v=>v.classList.toggle('selected',v===b));updateSelection(null);};return b;}
}

function showTutorial(level){
  const key=level.tutorial.toUpperCase(),container=$('tutorialText'),count=Number(strings[`${key}_META`]??0);container.replaceChildren();
  for(let i=1;i<=count;i++){const meta=strings[`${key}_${i}_META`]?.match(/^\((-?[\d.]+),([\d.]+)\)\s+([\d.]+)(?:\s+([\d.]+))?/);if(!meta)continue;const rawX=Number(meta[1]),x=Math.abs(rawX),y=Number(meta[2]),width=Number(meta[3])-12,scale=Number(meta[4]??1),copy=document.createElement('p');copy.className=`tutorial-copy${rawX<0?' left':''}`;copy.textContent=strings[`${key}_${i}`]??'';copy.style.left=`${x/4.8}%`;copy.style.top=`${y/8}%`;copy.style.width=`${width/4.8}%`;copy.style.fontSize=`${2.5*scale}cqw`;copy.style.transform=rawX<0?'translateY(-50%)':'translate(-50%,-50%)';container.append(copy);}
  $('closeTutorial').textContent=t('PlayLevel','Play level');$('tutorialOverlay').hidden=false;$('closeTutorial').onclick=()=>{$('tutorialOverlay').hidden=true;game.paused=false;audioBank?.play('menu');};
}

function showPauseMenu(level,paused){
  const overlay=$('gameOverlay');$('pauseGame').textContent=paused?t('Resume','Resume'):t('Pause','Pause');if(!paused){overlay.hidden=true;overlay.classList.remove('native-runtime');overlay.replaceChildren();return;}
  overlay.classList.add('native-runtime');overlay.hidden=false;overlay.innerHTML='<div class="pause-panel"><button class="action" id="pauseResume"></button><button class="action" id="pauseQuit"></button><button class="action" id="pauseRestart"></button><button class="action" id="pauseOptions"></button></div>';
  $('pauseResume').textContent=t('Resume','Resume');$('pauseQuit').textContent=t('QuitLevel','Quit level');$('pauseRestart').textContent=t('RestartLevel','Restart level');$('pauseOptions').textContent=t('Options','Options');$('pauseResume').onclick=()=>game?.togglePause();$('pauseQuit').onclick=()=>showPauseConfirmation(level,()=>{game?.destroy();game=null;clearSave();showMainMenu();});$('pauseRestart').onclick=()=>showPauseConfirmation(level,()=>startLevel(level));$('pauseOptions').onclick=()=>showPauseOptions(level);
}

function showPauseConfirmation(level,action){const overlay=$('gameOverlay');overlay.innerHTML='<div class="pause-subpanel"><h2></h2><p></p><button class="action" id="pauseNo"></button><button class="action primary" id="pauseYes"></button></div>';overlay.querySelector('h2').textContent=t('Confirmation','Confirmation');overlay.querySelector('p').textContent=t('QuitLevelConfirm','Are you sure?');$('pauseNo').textContent=t('No','No');$('pauseYes').textContent=t('Yes','Yes');$('pauseNo').onclick=()=>showPauseMenu(level,true);$('pauseYes').onclick=action;}

function showPauseOptions(level){
  const overlay=$('gameOverlay');overlay.innerHTML='<div class="pause-subpanel"><h2></h2><div class="pause-options" id="pauseOptionRows"></div><button class="ghost" id="pauseOptionBack"></button></div>';overlay.querySelector('h2').textContent=t('Options','Options');const rows=$('pauseOptionRows'),labels=()=>({sound:options.sound?t('SoundOn','Sound on'):t('SoundOff','Sound off'),placeAboveFinger:options.placeAboveFinger?t('PlaceAboveTouch','Place above touch'):t('PlaceAtTouch','Place at touch'),healthBars:options.healthBars?t('CreepHealthVisible','Creep health visible'):t('CreephealthHidden','Creep health hidden'),hardcore:options.hardcore?t('HardcoreMode','Hardcore mode'):t('NoviceMode','Novice mode')});for(const [key,label] of Object.entries(labels())){const row=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=options[key];input.onchange=()=>{options[key]=input.checked;saveOptions();if(game){game.healthBars=options.healthBars;game.placeAboveFinger=options.placeAboveFinger;game.hardcore=options.hardcore;}showPauseOptions(level);};row.append(label,input);rows.append(row);}$('pauseOptionBack').textContent=t('Back','Back');$('pauseOptionBack').onclick=()=>showPauseMenu(level,true);
}

function showPreGame(level,saved){game.paused=true;const overlay=$('gameOverlay'),high=profile.highScore(level);$('gameScreen').classList.add('pregame-open');overlay.classList.add('native-pregame');overlay.style.backgroundImage=artBackground(assets.preGame,'.08');overlay.hidden=false;overlay.innerHTML=`<div class="pregame-card"><h2></h2><p class="pregame-leaderboard"></p><p class="pregame-score"></p><button class="action primary" id="playMission"></button><button class="ghost" id="cancelMission"></button></div>`;overlay.querySelector('h2').textContent=level.name;overlay.querySelector('.pregame-leaderboard').textContent=t('Leaderboard','Leaderboard');overlay.querySelector('.pregame-score').textContent=high?`${t('YourHighScore','Your high score')}: ${high.score.toLocaleString()}`:'—';$('playMission').textContent=saved?t('Continue','Continue'):t('PlayLevel','Play level');$('cancelMission').textContent=t('Back','Back');$('playMission').onclick=()=>{$('gameScreen').classList.remove('pregame-open');overlay.classList.remove('native-pregame');overlay.hidden=true;overlay.style.backgroundImage='';const tutorial=assets.tutorials[level.tutorial];if(tutorial&&!saved){$('tutorialImage').src=tutorial.src;showTutorial(level);}else game.paused=false;};$('cancelMission').onclick=()=>{$('gameScreen').classList.remove('pregame-open');overlay.classList.remove('native-pregame');game.destroy();game=null;renderLevels();show($('levelScreen'));};}

function showGameOver(level,won,score,result){
  clearSave();clearTimeout(gameOverUnlockTimer);$('gameScreen').classList.remove('pregame-open');const overlay=$('gameOverlay'),previous=profile.highScore(level),isNew=won&&(!previous||score>previous.score);profile.record(level,result);overlay.classList.remove('native-pregame');overlay.classList.add('native-runtime');overlay.style.backgroundImage='';overlay.hidden=false;const taunts=Array.from({length:20},(_,i)=>strings[`Taunt${i+1}`]).filter(Boolean),note=won?(isNew?`${t('NewHighScore','New high score')} · ${score.toLocaleString()}`:''):(taunts[Math.floor(Math.random()*taunts.length)]??'');overlay.innerHTML=`<div class="game-over-panel"><div class="game-over-band">${won?'<canvas class="game-over-badge" width="116" height="112"></canvas>':''}<p class="game-over-score"></p><h2 class="game-over-title"></h2><p class="game-over-note"></p><p class="game-over-tap"></p></div></div>`;overlay.querySelector('.game-over-score').textContent=isNew?t('NewHighScore','New high score'):'';overlay.querySelector('.game-over-title').textContent=won?t('LevelComplete','Level complete'):t('GameOver','Game over');overlay.querySelector('.game-over-note').textContent=note;overlay.querySelector('.game-over-tap').textContent=t('TapToContinue','Tap to continue');
  const badge=overlay.querySelector('.game-over-badge');if(badge&&assets.buttons){const sy=result.lives===level.lives?452:level.endless?324:388,ctx=badge.getContext('2d');ctx.globalCompositeOperation='lighter';ctx.drawImage(assets.buttons,414,sy,58,56,0,0,116,112);}
  const unlockAt=performance.now()+2000;overlay.onclick=()=>{if(performance.now()>=unlockAt)showMainMenu();};gameOverUnlockTimer=setTimeout(()=>overlay.classList.add('unlocked'),2000);
}
function towerColor(type){return {BLASTER:'#55ff84',LASER:'#29aaff',MISSILE:'#ff4778',SHOCK:'#fff35c',THUMP:'#ff55ed',POP:'#c260ff'}[type]??'#fff';}
$('toggleDesktopPanel').onclick=()=>{const open=$('gameScreen').classList.toggle('desktop-panel-open');$('toggleDesktopPanel').setAttribute('aria-expanded',String(open));$('toggleDesktopPanel').textContent=open?'Hide desktop controls':'Desktop controls';};
$('startWave').onclick=()=>game?.startWave();$('upgradeTower').onclick=()=>game?.upgrade();$('laserLock').onclick=()=>game?.toggleLaserLock();$('linkTower').onclick=()=>game?.beginLink();$('sellTower').onclick=()=>game?.sell();$('pauseGame').onclick=()=>game?.togglePause();$('backToLevels').onclick=()=>{game?.destroy();game=null;$('tutorialOverlay').hidden=true;renderLevels();show($('levelScreen'));};addEventListener('beforeunload',()=>game?.persist());
