import { ARCHIVE_AUDIO_FILES, AudioBank } from './audio.js';
import { openZip } from './zip.js';
import { parseLevel, upgradeCost } from './core.js';
import { Game } from './game.js';
import { ACHIEVEMENTS, ProfileStore } from './profile.js';
import { loadArchiveStrings } from './resources.js';
import { BASE_RE, classifyName, buildLevels } from './level-index.js';
import { entries as bundledEntries } from './bundled-levels.js';
import { entries as lhcEntries } from './lhc-levels.js';
import { entries as xlEntries } from './xl-levels.js';
import { createProceduralSeed, entryFromProceduralSourceName, generateProceduralEntry, normalizeProceduralSeed, normalizeProceduralState, PROCEDURAL_DIFFICULTIES, PROCEDURAL_ECONOMIES, PROCEDURAL_SIZES } from './procedural-levels.js';
import { strings as bundledStrings } from './bundled-strings.js';
import { createSynthAudioBank } from './synth-audio.js';
import { cacheOriginalAssets, clearCachedOriginalAssets, hasCachedOriginalAssets, readCachedOriginalAssets } from './archive-cache.js';
import { detectInstallSuggestionPlatform, hasExportableProgress, installSuggestionDismissKey, installSuggestionDismissalActive } from './install-suggestion.js';

const $=id=>document.getElementById(id),SAVE_KEY='swarm-web-save-v1',OPTIONS_KEY='swarm-web-options-v1',PROCEDURAL_KEY='swarm-web-procedural-v1',PRESENTATION_KEY='swarm-web-presentation-v1';
let archiveCacheAvailable=false,presentationMode=readPresentationMode(),levels=[],loadedLevelEntries=[],assets={},strings={},game,audioBank,currentDifficulty='Easy',currentCampaign='swarm',options=readOptions(),proceduralState=readProceduralState(),gameOverUnlockTimer=0,installPrompt=null,storagePersistent=false,installSuggestionShown=false,installSuggestionPlatform=null;
let profile;try{profile=new ProfileStore(localStorage);}catch{profile=new ProfileStore(null);}
const screens=[$('loader'),$('mainMenuScreen'),$('levelScreen'),$('gameScreen')];

function show(screen){screens.forEach(s=>s.hidden=s!==screen);document.body.dataset.screen=screen.id;if(screen===$('levelScreen'))maybeShowInstallSuggestion();else $('installSuggestionPrompt').hidden=true;}
function setStatus(text,error=false){$('loadStatus').textContent=text;$('loadStatus').style.color=error?'#ff7584':'';}
function t(key,fallback){return strings[key]??fallback;}
function readOptions(){const defaults={sound:true,healthBars:true,hardcore:true,placeAboveFinger:true};try{return {...defaults,...JSON.parse(localStorage.getItem(OPTIONS_KEY))};}catch{return defaults;}}
function saveOptions(){try{localStorage.setItem(OPTIONS_KEY,JSON.stringify(options));}catch{}if(audioBank)audioBank.enabled=options.sound;}
function readProceduralState(){try{return normalizeProceduralState(JSON.parse(localStorage.getItem(PROCEDURAL_KEY)));}catch{return normalizeProceduralState(null);}}
function saveProceduralState(){try{localStorage.setItem(PROCEDURAL_KEY,JSON.stringify(proceduralState));}catch{}}
function readPresentationMode(){try{return localStorage.getItem(PRESENTATION_KEY)==='original'?'original':'procedural';}catch{return'procedural';}}
function savePresentationMode(mode){presentationMode=mode;try{localStorage.setItem(PRESENTATION_KEY,mode);}catch{}updatePresentationToggle();}
function readSave(){try{const save=JSON.parse(localStorage.getItem(SAVE_KEY));return save?.version===1&&save.state?.version===1?save:null;}catch{return null;}}
function storeSave(level,state){try{localStorage.setItem(SAVE_KEY,JSON.stringify({version:1,level:level.sourceName,state}));}catch{}}
function clearSave(){try{localStorage.removeItem(SAVE_KEY);}catch{}}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
async function requestPersistentStorage(){try{if(!navigator.storage?.persisted)return false;storagePersistent=await navigator.storage.persisted();if(!storagePersistent&&navigator.storage.persist)storagePersistent=await navigator.storage.persist();return storagePersistent;}catch{return false;}}
async function registerPwa(){addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;revealAndroidInstallAction();});addEventListener('appinstalled',()=>{installPrompt=null;$('installSuggestionPrompt').hidden=true;requestPersistentStorage();});requestPersistentStorage();if(!('serviceWorker'in navigator)||!isSecureContext)return;try{await navigator.serviceWorker.register(new URL('../sw.js',import.meta.url));}catch(error){console.warn('Offline app support is unavailable.',error);}}
function exportUserData(){game?.persist();const payload={format:'swarm-web-backup',version:1,exportedAt:new Date().toISOString(),profile:profile.data,options,proceduralState,save:readSave()},url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`geodefense-swarm-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
async function importUserData(file){const payload=JSON.parse(await file.text());if(payload?.format!=='swarm-web-backup'||payload.version!==1||payload.profile?.version!==1)throw new Error('This is not a valid geoDefense Swarm backup.');localStorage.setItem(profile.key,JSON.stringify(payload.profile));profile=new ProfileStore(localStorage);options={...readOptions(),...(payload.options??{})};saveOptions();proceduralState=normalizeProceduralState(payload.proceduralState);saveProceduralState();if(payload.save?.version===1&&payload.save.state?.version===1)localStorage.setItem(SAVE_KEY,JSON.stringify(payload.save));else clearSave();rebuildLevels();await requestPersistentStorage();await showMainMenu();}
function appendPwaTools(body){const panel=document.createElement('div'),status=document.createElement('p'),actions=document.createElement('div'),platform=detectInstallSuggestionPlatform(navigator);panel.className='pwa-panel';status.className='pwa-status';actions.className='pwa-actions';status.textContent=isStandalone()?'Installed app mode is active. Game data is isolated from Safari and eligible for persistent storage.':storagePersistent?'This browser granted persistent storage. Install the game for the most reliable offline play.':platform==='mac'?'In Safari, use File → Add to Dock or Share → Add to Dock for separate app storage and offline play.':platform==='ios'?'Use Share → Add to Home Screen and keep “Open as Web App” enabled to protect game data from Safari’s seven-day cleanup.':'Install the game for full-screen and offline play.';panel.append(status);if(!isStandalone()&&installPrompt){const install=document.createElement('button');install.className='action primary';install.textContent='Install game';install.onclick=async()=>{await installPrompt.prompt();installPrompt=null;$('menuOptions').onclick();};actions.append(install);}const backup=document.createElement('button'),restore=document.createElement('button');backup.className='ghost';backup.textContent='Export save backup';backup.onclick=exportUserData;restore.className='ghost';restore.textContent='Import save backup';restore.onclick=()=>$('backupInput').click();actions.append(backup,restore);panel.append(actions);body.append(panel);}
function hasUserProgress(){return hasExportableProgress(readSave(),profile.data);}
function revealAndroidInstallAction(){if(installSuggestionPlatform!=='android'||$('installSuggestionPrompt').hidden||!installPrompt)return;$('installSuggestionSteps').textContent='No app store or account needed.';$('acceptInstallSuggestion').hidden=false;$('dismissInstallSuggestion').className='ghost';}
function maybeShowInstallSuggestion(){if(installSuggestionShown||isStandalone())return;const platform=detectInstallSuggestionPlatform(navigator);if(!platform)return;const sessionKey=`swarm-web-${platform}-install-shown`;let dismissed=false,shownThisSession=false;try{dismissed=installSuggestionDismissalActive(localStorage.getItem(installSuggestionDismissKey(platform)));shownThisSession=sessionStorage.getItem(sessionKey)==='1';}catch{}if(dismissed||shownThisSession)return;installSuggestionShown=true;installSuggestionPlatform=platform;try{sessionStorage.setItem(sessionKey,'1');}catch{}const android=platform==='android',hasProgress=hasUserProgress();$('installSuggestionKicker').textContent=android?'optional app mode':'keep your progress';$('installSuggestionTitle').textContent=android?'Play like an app':'Install geoDefense';$('installSuggestionCopy').textContent=android?'Installing is optional. Add geoDefense to your phone for a smoother game experience.':`Safari may remove website data after extended inactivity. The installed game keeps separate app storage and works offline.${hasProgress?' Export your existing progress before installing.':''}`;$('installSuggestionSteps').textContent=android?(installPrompt?'No app store or account needed.':'Use your browser menu and choose Install app or Add to Home screen.'):platform==='ios'?'Tap Share, choose Add to Home Screen, then keep “Open as Web App” enabled if shown.':'In Safari, choose File → Add to Dock, or Share → Add to Dock.';$('installSuggestionBenefits').hidden=!android;$('installSuggestionBackup').hidden=android||!hasProgress;$('acceptInstallSuggestion').hidden=!android||!installPrompt;$('dismissInstallSuggestion').className=android&&installPrompt?'ghost':'action primary';$('installSuggestionPrompt').hidden=false;}
function dismissInstallSuggestion(){if(installSuggestionPlatform)try{localStorage.setItem(installSuggestionDismissKey(installSuggestionPlatform),String(Date.now()));}catch{}$('installSuggestionPrompt').hidden=true;}
async function acceptInstallSuggestion(){const prompt=installPrompt;if(!prompt)return;$('installSuggestionPrompt').hidden=true;try{await prompt.prompt();await prompt.userChoice;}finally{installPrompt=null;dismissInstallSuggestion();}}
$('closeInstallSuggestion').onclick=dismissInstallSuggestion;$('dismissInstallSuggestion').onclick=dismissInstallSuggestion;$('acceptInstallSuggestion').onclick=acceptInstallSuggestion;$('installSuggestionBackup').onclick=()=>{exportUserData();dismissInstallSuggestion();};
async function loadImageBlob(blob){if(!blob)return null;const url=URL.createObjectURL(blob),img=new Image();img.src=url;img.objectUrl=url;try{await img.decode();return img;}catch(error){URL.revokeObjectURL(url);throw error;}}
function disposeAssets(){const visit=value=>{if(value?.objectUrl)URL.revokeObjectURL(value.objectUrl);else if(value&&typeof value==='object')Object.values(value).forEach(visit);};visit(assets);assets={};}
function artBackground(img,shade='.34'){return img?`linear-gradient(rgba(0,4,15,${shade}),rgba(0,4,15,${shade})),url("${img.objectUrl}")`:'';}

// The game ships bundled level XML + localized strings and renders art/audio
// procedurally, so it boots straight to the menu with no archive. Importing the
// original .xap/.ipa is an OPTIONAL override that swaps in the authentic raster
// sprites/art and WAV audio; both paths funnel through the same apply* helpers.
const RASTER_PNGS=['Content/BackdropP1.png','Content/Honeycomb.png','Content/Towers.png','Content/Creeps.png','Content/Shots.png','Content/MainMenu.png','Content/LevelSelect.png','Content/PreGame.png','Content/Buttons.png','Content/BuildBar.png','Content/TowerBar.png','Content/ScoreBar.png','Content/TouchIndicators.png','Content/Credits.png',...Array.from({length:9},(_,i)=>`Content/Tutorials/t${i+1}.png`)];
// The LHC pack is a repo-bundled fan campaign (procedural, archive-independent),
// so it rides along in both the bundled boot and an original-archive import.
function proceduralEntries(){const out=[];for(const mode of PROCEDURAL_ECONOMIES)for(const size of PROCEDURAL_SIZES)for(const difficulty of PROCEDURAL_DIFFICULTIES)for(const seed of proceduralState.sets[mode][size][difficulty])out.push(generateProceduralEntry({seed,difficulty,economyMode:mode,size}));return out;}
function rebuildLevels(){levels=buildLevels([...loadedLevelEntries,...lhcEntries,...xlEntries,...proceduralEntries()],parseLevel);}
function applyLevels(entries){loadedLevelEntries=[...entries];rebuildLevels();}
function applyStrings(map){strings=map;assets.strings=strings;localizeMenu();}
async function collectEntries(opened){const out=[];for(const z of opened)for(const name of z.names)if(classifyName(name))out.push({sourceName:name,xml:await z.text(name)});return out;}
async function collectOriginalAssets(files){
  const opened=await Promise.all(files.map(openZip)),mainArchive=opened.find(z=>z.names.some(n=>BASE_RE.test(n)));
  if(!mainArchive)throw new Error('Include the original Windows Phone .xap.');
  const audioArchive=opened.find(z=>z.names.some(n=>n.toLowerCase().endsWith('/blastershot.wav'))),images={},sounds={};
  await Promise.all(RASTER_PNGS.map(async name=>{if(mainArchive.has(name))images[name]=new Blob([await mainArchive.bytes(name)],{type:'image/png'});}));
  if(audioArchive)await Promise.all(Object.entries(ARCHIVE_AUDIO_FILES).map(async([key,file])=>{const name=audioArchive.names.find(n=>n.toLowerCase().endsWith('/'+file.toLowerCase()));if(name)sounds[key]=new Blob([await audioArchive.bytes(name)],{type:'audio/wav'});}));
  return {levels:await collectEntries(opened),strings:await loadArchiveStrings(mainArchive),images,sounds};
}
async function applyRasterAssets(images){disposeAssets();const loaded=await Promise.all(RASTER_PNGS.map(name=>loadImageBlob(images[name])));const [backdrop,honeycomb,towers,creeps,shots,mainMenu,levelSelect,preGame,buttons,buildBar,towerBar,scoreBar,touchIndicators,credits,...tutorials]=loaded;assets={backdrop,honeycomb,towers,creeps,shots,mainMenu,levelSelect,preGame,buttons,buildBar,towerBar,scoreBar,touchIndicators,credits,tutorials:Object.fromEntries(tutorials.map((img,i)=>[`t${i+1}`,img]))};assets.strings=strings;$('mainMenuScreen').style.backgroundImage=artBackground(mainMenu,'.12');$('levelScreen').style.backgroundImage=artBackground(levelSelect,'.68');}
function updatePresentationToggle(){const button=$('changeArchive');button.hidden=!archiveCacheAvailable&&presentationMode!=='original';button.textContent=presentationMode==='original'?'Use procedural graphics':'Use original graphics';button.setAttribute('aria-pressed',String(presentationMode==='original'));}
function refreshPresentationSurfaces(){if(game)game.setAssets(assets);const pregame=$('gameOverlay').classList.contains('native-pregame');if(pregame)$('gameOverlay').style.backgroundImage=artBackground(assets.preGame,'.08');if(game&&!$('tutorialOverlay').hidden){const tutorial=assets.tutorials?.[game.level.tutorial];if(tutorial){$('tutorialImage').src=tutorial.src;showTutorial(game.level);}else showProceduralTutorial(game.level);}}
async function applyOriginalAssets(payload,{preserveGame=false}={}){if(!preserveGame){game?.destroy();game=null;applyLevels(payload.levels);}applyStrings(payload.strings);setStatus('Preparing original presentation…');await applyRasterAssets(payload.images);refreshPresentationSurfaces();audioBank?.dispose();audioBank=AudioBank.fromBlobs(payload.sounds)??await createSynthAudioBank();audioBank.enabled=options.sound;savePresentationMode('original');setStatus('');if(!preserveGame)showMainMenu();}
async function bootBundled({preserveGame=false}={}){if(!preserveGame){game?.destroy();game=null;applyLevels(bundledEntries);}disposeAssets();const lang=(globalThis.navigator?.language??'en').slice(0,2).toLowerCase();applyStrings(bundledStrings[lang]??bundledStrings.en);$('mainMenuScreen').style.backgroundImage='';$('levelScreen').style.backgroundImage='';refreshPresentationSurfaces();audioBank?.dispose();audioBank=await createSynthAudioBank();audioBank.enabled=options.sound;savePresentationMode('procedural');setStatus('');if(!preserveGame)showMainMenu();}
async function restoreOriginalAssets({preserveGame=false}={}){setStatus('Restoring cached original graphics…');if(!preserveGame)show($('loader'));await applyOriginalAssets(await readCachedOriginalAssets(),{preserveGame});}
async function initialize(){try{archiveCacheAvailable=await hasCachedOriginalAssets();}catch(error){console.warn('Persistent original-asset storage is unavailable.',error);archiveCacheAvailable=false;}if(presentationMode==='original'&&archiveCacheAvailable){try{await restoreOriginalAssets();return;}catch(error){console.error('Unable to restore cached original assets.',error);try{await clearCachedOriginalAssets();}catch{}archiveCacheAvailable=false;}}await bootBundled();}

$('archiveInput').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;try{setStatus(`Reading ${files.length} archive${files.length===1?'':'s'} locally…`);const payload=await collectOriginalAssets(files);await applyOriginalAssets(payload);try{await cacheOriginalAssets(payload);archiveCacheAvailable=true;updatePresentationToggle();}catch(cacheError){console.warn('Original graphics are active but could not be cached.',cacheError);}}catch(err){console.error(err);setStatus(err.message,true);}});

// Menu structure: two core campaigns (base Swarm, Original geoDefense) plus a
// data-driven list of expansion packs. Each campaign's Easy/Medium/Hard (and
// Swarm's Bonus/Level Pack 1) live behind the level-screen difficulty tabs, so a
// single menu button opens the whole set. Ship a new expansion by adding its
// levels module (merged in applyLevels) and one entry here.
const EXPANSIONS=[{campaign:'lhc',title:'LHC // Breach Grid'},{campaign:'xl',title:'Swarm XL (WIP)'},{campaign:'procedural',title:'Procedural Swarm'}];
const CAMPAIGN_TITLES={swarm:'geoDefense Swarm',classic:'Original geoDefense',...Object.fromEntries(EXPANSIONS.map(e=>[e.campaign,e.title]))};
function campaignDifficulties(campaign){return ['Easy','Medium','Hard','Bonus'].filter(d=>levels.some(l=>(l.campaign??'swarm')===campaign&&l.difficulty===d));}
function firstDifficulty(campaign){return campaignDifficulties(campaign)[0]??'Easy';}
function openCampaign(campaign){enterDifficulty(firstDifficulty(campaign),campaign);}
function resolveSavedLevel(save){if(!save)return null;const loaded=levels.find(level=>level.sourceName===save.level);if(loaded)return loaded;try{const entry=entryFromProceduralSourceName(save.level);return entry?buildLevels([entry],parseLevel)[0]??null:null;}catch(err){console.warn('Unable to reconstruct procedural save',err);return null;}}

async function showMainMenu(){game?.destroy();game=null;audioBank?.play('menu');$('menuDialog').hidden=true;const save=readSave(),savedLevel=resolveSavedLevel(save);$('continueGame').hidden=!savedLevel;if(savedLevel)$('continueGame').onclick=()=>startLevel(savedLevel,save.state);$('menuClassic').hidden=!levels.some(l=>l.campaign==='classic');const active=EXPANSIONS.filter(e=>levels.some(l=>l.campaign===e.campaign));$('expansionsGroup').hidden=!active.length;$('expansionButtons').replaceChildren(...active.map(e=>{const b=document.createElement('button');b.className='action';b.textContent=e.title;b.onclick=()=>openCampaign(e.campaign);return b;}));show($('mainMenuScreen'));}
function localizeMenu(){$('continueGame').textContent=t('ContinueSaved','Continue saved mission');$('menuSwarm').textContent=CAMPAIGN_TITLES.swarm;$('menuClassic').textContent=CAMPAIGN_TITLES.classic;$('menuLeaderboards').textContent=t('Leaderboards','Leaderboards');$('menuAchievements').textContent=t('Achievements','Achievements');$('menuOptions').textContent=t('Options','Options');$('closeMenuDialog').textContent=t('Back','Back');$('backToMenu').textContent=`← ${t('MainMenu','Main menu')}`;$('levelScreen').querySelector('.section-heading h2').textContent=t('SelectLevel','Select level');}
function enterDifficulty(difficulty,campaign='swarm'){currentCampaign=campaign;currentDifficulty=difficulty;$('levelScreen').querySelector('.section-heading h2').textContent=CAMPAIGN_TITLES[campaign]??t('SelectLevel','Select level');renderLevels();audioBank?.play('menu');show($('levelScreen'));}
$('menuSwarm').onclick=()=>openCampaign('swarm');$('menuClassic').onclick=()=>openCampaign('classic');$('backToMenu').onclick=showMainMenu;

function openMenuDialog(title){$('menuDialogTitle').textContent=title;$('menuDialogBody').replaceChildren();$('menuDialog').hidden=false;audioBank?.play('menu');return $('menuDialogBody');}
$('closeMenuDialog').onclick=()=>{$('menuDialog').hidden=true;audioBank?.play('menu');};
$('menuOptions').onclick=()=>{const body=openMenuDialog(t('Options','Options')),labels={sound:options.sound?t('SoundOn','Sound on'):t('SoundOff','Sound off'),placeAboveFinger:options.placeAboveFinger?t('PlaceAboveTouch','Place above touch'):t('PlaceAtTouch','Place at touch'),healthBars:options.healthBars?t('CreepHealthVisible','Creep health visible'):t('CreephealthHidden','Creep health hidden'),hardcore:options.hardcore?t('HardcoreMode','Hardcore mode'):t('NoviceMode','Novice mode')};for(const key of Object.keys(labels)){const row=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=options[key];input.onchange=()=>{options[key]=input.checked;saveOptions();$('menuOptions').onclick();};row.append(labels[key],input);body.append(row);}const loadBtn=document.createElement('button');loadBtn.className='action';loadBtn.textContent=presentationMode==='original'?'Reload original archives':archiveCacheAvailable?'Replace cached original archives':'Load original archives (optional)';loadBtn.style.marginTop='18px';loadBtn.onclick=()=>$('archiveInput').click();body.append(loadBtn);if(presentationMode==='original'||archiveCacheAvailable){const switchBtn=document.createElement('button');switchBtn.className='ghost';switchBtn.textContent=presentationMode==='original'?'Use procedural graphics':'Use original graphics';switchBtn.style.marginTop='8px';switchBtn.onclick=()=>{$('menuDialog').hidden=true;togglePresentation();};body.append(switchBtn);}const aboutBtn=document.createElement('button');aboutBtn.id='menuAbout';aboutBtn.className='action';aboutBtn.textContent=t('About','About');aboutBtn.style.marginTop='8px';aboutBtn.onclick=showAbout;body.append(aboutBtn);const about=document.createElement('p');about.textContent='Critical Thought Games, LLC · Browser preservation engine';about.style.marginTop='16px';body.append(about);};
const openOptionsDialog=$('menuOptions').onclick;
$('menuOptions').onclick=()=>{openOptionsDialog();appendPwaTools($('menuDialogBody'));};
$('backupInput').addEventListener('change',async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{await importUserData(file);}catch(error){console.error(error);alert(error.message);}});
function showAbout(){if(!assets.credits)return;$('aboutImage').src=assets.credits.src;$('aboutOverlay').hidden=false;audioBank?.play('menu');}
$('aboutOverlay').onclick=()=>{$('aboutOverlay').hidden=true;audioBank?.play('menu');};
$('menuLeaderboards').onclick=()=>{const body=openMenuDialog(t('Leaderboards','Leaderboards')),list=document.createElement('div');list.className='profile-list';const rows=profile.leaderboard();if(!rows.length)list.textContent='No completed missions yet.';for(const score of rows){const row=document.createElement('div');row.className='profile-row';const name=document.createElement('span'),value=document.createElement('strong');name.textContent=score.name;value.textContent=score.score.toLocaleString();row.append(name,value);list.append(row);}body.append(list);};
$('menuAchievements').onclick=()=>{const body=openMenuDialog(t('Achievements','Achievements')),list=document.createElement('div'),earned=new Set(profile.data.achievements);list.className='profile-list';for(const [code,label] of Object.entries(ACHIEVEMENTS)){const row=document.createElement('div');row.className='profile-row'+(earned.has(code)?'':' locked');const name=document.createElement('span'),state=document.createElement('strong');name.textContent=label;state.textContent=earned.has(code)?'UNLOCKED':'LOCKED';row.append(name,state);list.append(row);}body.append(list);};

async function togglePresentation(){const button=$('changeArchive'),preserveGame=!!game;button.disabled=true;try{if(presentationMode==='original')await bootBundled({preserveGame});else await restoreOriginalAssets({preserveGame});}catch(error){console.error('Unable to switch presentation.',error);try{await clearCachedOriginalAssets();}catch{}archiveCacheAvailable=false;await bootBundled({preserveGame});}finally{button.disabled=false;}}
$('changeArchive').onclick=togglePresentation;
function levelBadgeRow(level){const high=profile.highScore(level);return level.endless?(high?324:260):(high?(high.livesLost===0?452:388):null);}
function makeBadge(sy){const c=document.createElement('canvas');c.width=58;c.height=56;c.className='level-badge';const cx=c.getContext('2d');if(assets.buttons){cx.globalCompositeOperation='lighter';cx.drawImage(assets.buttons,414,sy,58,56,0,0,58,56);}else drawBadge(cx,sy,58,56);return c;}
function drawBadge(ctx,sy,w,h){const r=Math.min(w,h)*.42;ctx.save();ctx.globalCompositeOperation='lighter';ctx.translate(w/2,h/2);const kind=sy===452?'perfect':sy===388?'completed':sy===324?'endlessScored':'endless',col=kind==='perfect'?'#ffd54a':kind==='completed'?'#5affc0':'#8bd0ff';ctx.fillStyle=col;ctx.strokeStyle=col;ctx.lineWidth=2;if(kind==='endless'||kind==='endlessScored'){ctx.globalAlpha=kind==='endlessScored'?1:.5;ctx.font=`700 ${Math.round(r*1.7)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('∞',0,1);}else{ctx.beginPath();for(let i=0;i<10;i++){const a=Math.PI/5*i-Math.PI/2,rr=i%2?r*.45:r,x=Math.cos(a)*rr,y=Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();if(kind==='perfect'){ctx.globalAlpha=.9;ctx.strokeStyle='#fff';ctx.stroke();}}ctx.restore();}
function setProceduralError(message=''){$('proceduralError').textContent=message;}
function replacementProceduralSeeds(){const seeds=[];for(let guard=0;seeds.length<4&&guard<100;guard++){const seed=createProceduralSeed();if(!seeds.includes(seed))seeds.push(seed);}if(seeds.length<4)throw new Error('Unable to create four unique seeds.');return seeds;}
function commitProceduralSeeds(seeds){for(const seed of seeds)generateProceduralEntry({seed,difficulty:currentDifficulty,economyMode:proceduralState.economyMode,size:proceduralState.size});proceduralState.sets[proceduralState.economyMode][proceduralState.size][currentDifficulty]=seeds;saveProceduralState();rebuildLevels();}
function rerollProcedural(){const button=$('rerollProcedural');button.disabled=true;setProceduralError();try{commitProceduralSeeds(replacementProceduralSeeds());$('proceduralSeed').value='';renderLevels();}catch(err){console.error(err);setProceduralError(err.message);}finally{button.disabled=false;}}
function loadProceduralSeed(){setProceduralError();try{const seed=normalizeProceduralSeed($('proceduralSeed').value),current=proceduralState.sets[proceduralState.economyMode][proceduralState.size][currentDifficulty],next=[seed,...current.filter(value=>value!==seed)].slice(0,4);commitProceduralSeeds(next);$('proceduralSeed').value='';renderLevels();}catch(err){setProceduralError(err.message);}}
function renderProceduralTools(){const active=currentCampaign==='procedural',screen=$('levelScreen');screen.classList.toggle('procedural-campaign',active);$('proceduralTools').hidden=!active;if(!active)return;for(const [mode,id] of [['normal','proceduralNormal'],['random','proceduralRandom']]){const button=$(id);button.classList.toggle('active',proceduralState.economyMode===mode);button.setAttribute('aria-pressed',String(proceduralState.economyMode===mode));button.onclick=()=>{proceduralState.economyMode=mode;saveProceduralState();setProceduralError();renderLevels();};}for(const [size,id] of [['standard','proceduralStandardSize'],['xl','proceduralXlSize']]){const button=$(id);button.classList.toggle('active',proceduralState.size===size);button.setAttribute('aria-pressed',String(proceduralState.size===size));button.onclick=()=>{proceduralState.size=size;saveProceduralState();setProceduralError();renderLevels();};}$('rerollProcedural').onclick=rerollProcedural;$('loadProceduralSeed').onclick=loadProceduralSeed;$('proceduralSeed').onkeydown=event=>{if(event.key==='Enter')loadProceduralSeed();};}
function renderLevels(){let view=levels.filter(l=>(l.campaign??'swarm')===currentCampaign);if(currentCampaign==='procedural')view=view.filter(level=>level.procedural?.economyMode===proceduralState.economyMode&&level.procedural?.size===proceduralState.size);const difficulties=['Easy','Medium','Hard','Bonus'].filter(d=>view.some(l=>l.difficulty===d));if(!difficulties.includes(currentDifficulty))currentDifficulty=difficulties[0]??'Easy';renderProceduralTools();$('difficultyTabs').replaceChildren(...difficulties.map(d=>{const b=document.createElement('button');b.textContent=t(`${d}Levels`,d);b.className=d===currentDifficulty?'active':'';b.onclick=()=>{currentDifficulty=d;setProceduralError();renderLevels();};return b;}));let visible=view.filter(l=>l.difficulty===currentDifficulty);if(currentCampaign==='procedural'){const order=proceduralState.sets[proceduralState.economyMode][proceduralState.size][currentDifficulty];visible.sort((a,b)=>order.indexOf(a.procedural.seed)-order.indexOf(b.procedural.seed));}const cards=visible.map((level,index)=>{const b=document.createElement('button'),high=profile.highScore(level);b.className=`level-card${level.procedural?' procedural-level-card':''}`;b.innerHTML=`<span class="level-number">MISSION ${String(index+1).padStart(2,'0')}</span><h3></h3><p></p><small></small>`;b.querySelector('h3').textContent=level.name;b.querySelector('p').textContent=level.description;const score=high?`${t('YourHighScore','High score')} ${high.score.toLocaleString()}`:'';b.querySelector('small').textContent=level.procedural?`SEED ${level.procedural.seed} · ${level.procedural.size==='xl'?'XL · ':''}${level.procedural.economyMode==='normal'?'NORMAL':'RANDOM'}${score?` · ${score}`:''}`:score;const badge=levelBadgeRow(level);if(badge!=null)b.append(makeBadge(badge));b.onclick=()=>startLevel(level);return b;});$('levelGrid').replaceChildren(...cards);}

function startLevel(level,savedState=null){game?.destroy();clearTimeout(gameOverUnlockTimer);if(!savedState)clearSave();$('gameScreen').classList.remove('pregame-open','desktop-panel-open');$('toggleDesktopPanel').setAttribute('aria-expanded','false');$('toggleDesktopPanel').textContent='Desktop controls';$('gameOverlay').classList.remove('native-pregame','native-runtime');$('gameOverlay').onclick=null;show($('gameScreen'));audioBank?.play('menu');$('difficultyLabel').textContent=level.difficulty;$('levelName').textContent=level.name;$('levelDescription').textContent=level.description;$('gameOverlay').hidden=true;$('tutorialOverlay').hidden=true;$('pauseGame').textContent='Pause';$('backToLevels').textContent='← Missions';$('multiplier').textContent='×1';const buttons=level.towers.filter(t=>level.pathMode||t.type!=='POP').map(t=>makeTowerButton(t));$('towerButtons').replaceChildren(...buttons);
  const updateSelection=t=>{buttons.forEach(v=>v.classList.remove('selected'));$('upgradeTower').disabled=!t||t.level>=7||t.upgradeRemaining>0;$('upgradeTower').textContent=t&&t.level<7?(t.upgradeRemaining>0?`Upgrading · ${Math.ceil(t.upgradeRemaining)}s`:`Upgrade · ${upgradeCost(t.cost,t.level)} credits`):'Upgrade selected tower';$('sellTower').disabled=!t;$('sellTower').textContent=t?(t.type==='POP'?'Detonate Vortex':`Sell · ${Math.floor(t.value/2)} credits`):'Sell selected tower';$('linkTower').disabled=!t||(!['BLASTER','LASER','MISSILE'].includes(t.type)&&!(t.type==='POP'&&t.level===7));$('laserLock').disabled=!t||t.type!=='LASER'||t.level<3;$('laserLock').textContent=t?.lockedHeading?'Restore Laser tracking':'Lock Laser heading';};
  game=new Game($('game'),level,assets,{stats:s=>{$('cash').textContent=s.cash;$('lives').textContent=s.lives;$('wave').textContent=`${s.wave}/${s.total}`;$('score').textContent=s.score;$('multiplier').textContent=`×${s.multiplier}`;$('startWave').disabled=s.complete||s.waiting;$('startWave').textContent=s.complete?'All waves launched':s.waiting?'Spawning current swarm':`Launch next wave · ${Math.ceil(s.nextWave)}s`;},message:t=>$('gameMessage').textContent=t,selection:updateSelection,sound:key=>audioBank?.play(key),save:state=>storeSave(level,state),pause:p=>showPauseMenu(level,p),end:(won,score,result)=>showGameOver(level,won,score,result)},savedState,options);updateSelection(null);showPreGame(level,savedState);
  function makeTowerButton(tower){const b=document.createElement('button');let down=null,dragged=false,suppress=false;b.className='tower-button';const name=t(`${tower.type[0]+tower.type.slice(1).toLowerCase()}TowerName`,tower.type);b.innerHTML='<span class="tower-dot"></span>';b.append(`${name} · ${tower.cost}`);b.style.color=towerColor(tower.type);b.onpointerdown=e=>{if(e.button!==0)return;down={x:e.clientX,y:e.clientY};dragged=false;b.setPointerCapture?.(e.pointerId);};b.onpointermove=e=>{if(!down)return;if(!dragged&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)dragged=true;if(dragged)game.setBuildPreview(tower.type,e.clientX,e.clientY);};b.onpointerup=()=>{if(dragged){game.commitBuildPreview();suppress=true;}down=null;dragged=false;};b.onpointercancel=()=>{down=null;dragged=false;game.cancelBuildPreview();};b.onclick=()=>{if(suppress){suppress=false;return;}game.selectType(tower.type);buttons.forEach(v=>v.classList.toggle('selected',v===b));updateSelection(null);};return b;}
}

function showTutorial(level){
  const key=level.tutorial.toUpperCase(),container=$('tutorialText'),count=Number(strings[`${key}_META`]??0);container.replaceChildren();container.classList.remove('tutorial-procedural');
  for(let i=1;i<=count;i++){const meta=strings[`${key}_${i}_META`]?.match(/^\((-?[\d.]+),([\d.]+)\)\s+([\d.]+)(?:\s+([\d.]+))?/);if(!meta)continue;const rawX=Number(meta[1]),x=Math.abs(rawX),y=Number(meta[2]),width=Number(meta[3])-12,scale=Number(meta[4]??1),copy=document.createElement('p');copy.className=`tutorial-copy${rawX<0?' left':''}`;copy.textContent=strings[`${key}_${i}`]??'';copy.style.left=`${x/4.8}%`;copy.style.top=`${y/8}%`;copy.style.width=`${width/4.8}%`;copy.style.fontSize=`${2.5*scale}cqw`;copy.style.transform=rawX<0?'translateY(-50%)':'translate(-50%,-50%)';container.append(copy);}
  $('closeTutorial').textContent=t('PlayLevel','Play level');$('tutorialOverlay').hidden=false;$('closeTutorial').onclick=()=>{$('tutorialOverlay').hidden=true;game.paused=false;audioBank?.play('menu');};
}

// When the original tutorial screenshots aren't loaded, present the bundled
// localized tutorial text over a generated backdrop instead of skipping it.
let tutorialArtCache=null;
function proceduralTutorialArt(){
  if(tutorialArtCache)return tutorialArtCache;
  const c=document.createElement('canvas');c.width=480;c.height=800;const g=c.getContext('2d');
  const grad=g.createLinearGradient(0,0,0,800);grad.addColorStop(0,'#061024');grad.addColorStop(.55,'#03081a');grad.addColorStop(1,'#02040d');g.fillStyle=grad;g.fillRect(0,0,480,800);
  g.globalCompositeOperation='lighter';g.strokeStyle='rgba(60,150,210,.10)';g.lineWidth=1.5;const R=34,H=R*Math.sqrt(3);
  for(let row=-1;row*R*1.5<840;row++)for(let col=-1;col*H<520;col++){const x=col*H+(row%2?H/2:0),y=row*R*1.5;g.beginPath();for(let i=0;i<6;i++){const a=Math.PI/3*i+Math.PI/6,xp=x+Math.cos(a)*R,yp=y+Math.sin(a)*R;i?g.lineTo(xp,yp):g.moveTo(xp,yp);}g.closePath();g.stroke();}
  const bar=g.createLinearGradient(0,0,0,170);bar.addColorStop(0,'rgba(80,220,255,.22)');bar.addColorStop(1,'rgba(80,220,255,0)');g.fillStyle=bar;g.fillRect(0,0,480,170);
  g.globalCompositeOperation='source-over';g.strokeStyle='rgba(90,220,255,.35)';g.lineWidth=3;g.strokeRect(6,6,468,788);
  tutorialArtCache=c.toDataURL('image/png');return tutorialArtCache;
}
function showProceduralTutorial(level){
  if(!level.tutorial)return false;
  const key=level.tutorial.toUpperCase(),count=Number(strings[`${key}_META`]??0),paras=[];
  for(let i=1;i<=count;i++){const txt=strings[`${key}_${i}`];if(txt)paras.push(txt.replaceAll('\r',' '));}
  if(!paras.length)return false;
  $('tutorialImage').src=proceduralTutorialArt();
  const container=$('tutorialText');container.replaceChildren();container.classList.add('tutorial-procedural');
  const kicker=document.createElement('p');kicker.className='tutorial-proc-kicker';kicker.textContent='Mission Briefing';container.append(kicker);
  const title=document.createElement('h3');title.className='tutorial-proc-title';title.textContent=level.name;container.append(title);
  for(const text of paras){const p=document.createElement('p');p.className='tutorial-proc-copy';p.textContent=text;container.append(p);}
  $('closeTutorial').textContent=t('PlayLevel','Play level');$('tutorialOverlay').hidden=false;
  $('closeTutorial').onclick=()=>{$('tutorialOverlay').hidden=true;container.classList.remove('tutorial-procedural');game.paused=false;audioBank?.play('menu');};
  return true;
}

function showPauseMenu(level,paused){
  const overlay=$('gameOverlay');$('pauseGame').textContent=paused?t('Resume','Resume'):t('Pause','Pause');if(!paused){overlay.hidden=true;overlay.classList.remove('native-runtime');overlay.replaceChildren();return;}
  overlay.classList.add('native-runtime');overlay.hidden=false;overlay.innerHTML='<div class="pause-panel"><button class="action" id="pauseResume"></button><button class="action" id="pauseQuit"></button><button class="action" id="pauseRestart"></button><button class="action" id="pauseOptions"></button></div>';
  $('pauseResume').textContent=t('Resume','Resume');$('pauseQuit').textContent=t('QuitLevel','Quit level');$('pauseRestart').textContent=t('RestartLevel','Restart level');$('pauseOptions').textContent=t('Options','Options');$('pauseResume').onclick=()=>game?.togglePause();$('pauseQuit').onclick=()=>showPauseConfirmation(level,()=>{game?.destroy();game=null;clearSave();showMainMenu();});$('pauseRestart').onclick=()=>showPauseConfirmation(level,()=>startLevel(level));$('pauseOptions').onclick=()=>showPauseOptions(level);
}

function showPauseConfirmation(level,action){const overlay=$('gameOverlay');overlay.innerHTML='<div class="pause-subpanel"><h2></h2><p></p><button class="action" id="pauseNo"></button><button class="action primary" id="pauseYes"></button></div>';overlay.querySelector('h2').textContent=t('Confirmation','Confirmation');overlay.querySelector('p').textContent=t('QuitLevelConfirm','Are you sure?');$('pauseNo').textContent=t('No','No');$('pauseYes').textContent=t('Yes','Yes');$('pauseNo').onclick=()=>showPauseMenu(level,true);$('pauseYes').onclick=action;}

function showPauseOptions(level){
  const overlay=$('gameOverlay');overlay.innerHTML='<div class="pause-subpanel"><h2></h2><div class="pause-options" id="pauseOptionRows"></div><button class="ghost" id="pauseOptionBack"></button></div>';overlay.querySelector('h2').textContent=t('Options','Options');const rows=$('pauseOptionRows'),labels=()=>({sound:options.sound?t('SoundOn','Sound on'):t('SoundOff','Sound off'),placeAboveFinger:options.placeAboveFinger?t('PlaceAboveTouch','Place above touch'):t('PlaceAtTouch','Place at touch'),healthBars:options.healthBars?t('CreepHealthVisible','Creep health visible'):t('CreephealthHidden','Creep health hidden'),hardcore:options.hardcore?t('HardcoreMode','Hardcore mode'):t('NoviceMode','Novice mode')});for(const [key,label] of Object.entries(labels())){const row=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=options[key];input.onchange=()=>{options[key]=input.checked;saveOptions();if(game){game.healthBars=options.healthBars;game.placeAboveFinger=options.placeAboveFinger;game.hardcore=options.hardcore;}showPauseOptions(level);};row.append(label,input);rows.append(row);}$('pauseOptionBack').textContent=t('Back','Back');$('pauseOptionBack').onclick=()=>showPauseMenu(level,true);
}

function showPreGame(level,saved){game.paused=true;const overlay=$('gameOverlay'),high=profile.highScore(level);$('gameScreen').classList.add('pregame-open');overlay.classList.add('native-pregame');overlay.style.backgroundImage=artBackground(assets.preGame,'.08');overlay.hidden=false;overlay.innerHTML=`<div class="pregame-card"><h2></h2><p class="pregame-leaderboard"></p><p class="pregame-score"></p><p class="pregame-seed" hidden></p><button class="action primary" id="playMission"></button><button class="ghost" id="cancelMission"></button></div>`;overlay.querySelector('h2').textContent=level.name;overlay.querySelector('.pregame-leaderboard').textContent=t('Leaderboard','Leaderboard');overlay.querySelector('.pregame-score').textContent=high?`${t('YourHighScore','Your high score')}: ${high.score.toLocaleString()}`:'—';const seedLine=overlay.querySelector('.pregame-seed');if(level.procedural){seedLine.hidden=false;seedLine.textContent=`Seed ${level.procedural.seed} · ${level.procedural.size==='xl'?'XL · ':''}${level.procedural.economyMode==='normal'?'Normal':'Random'} economy`;}$('playMission').textContent=saved?t('Continue','Continue'):t('PlayLevel','Play level');$('cancelMission').textContent=t('Back','Back');$('playMission').onclick=()=>{$('gameScreen').classList.remove('pregame-open');overlay.classList.remove('native-pregame');overlay.hidden=true;overlay.style.backgroundImage='';const tutorial=assets.tutorials?.[level.tutorial];if(tutorial&&!saved){$('tutorialImage').src=tutorial.src;showTutorial(level);}else if(!saved&&showProceduralTutorial(level)){}else game.paused=false;};$('cancelMission').onclick=()=>{$('gameScreen').classList.remove('pregame-open');overlay.classList.remove('native-pregame');game.destroy();game=null;renderLevels();show($('levelScreen'));};}

function showGameOver(level,won,score,result){
  clearSave();clearTimeout(gameOverUnlockTimer);$('gameScreen').classList.remove('pregame-open');const overlay=$('gameOverlay'),previous=profile.highScore(level),isNew=won&&(!previous||score>previous.score);profile.record(level,result);overlay.classList.remove('native-pregame');overlay.classList.add('native-runtime');overlay.style.backgroundImage='';overlay.hidden=false;const taunts=Array.from({length:20},(_,i)=>strings[`Taunt${i+1}`]).filter(Boolean),note=won?(isNew?`${t('NewHighScore','New high score')} · ${score.toLocaleString()}`:''):(taunts[Math.floor(Math.random()*taunts.length)]??'');overlay.innerHTML=`<div class="game-over-panel"><div class="game-over-band">${won?'<canvas class="game-over-badge" width="116" height="112"></canvas>':''}<p class="game-over-score"></p><h2 class="game-over-title"></h2><p class="game-over-note"></p><p class="game-over-tap"></p></div></div>`;overlay.querySelector('.game-over-score').textContent=isNew?t('NewHighScore','New high score'):'';overlay.querySelector('.game-over-title').textContent=won?t('LevelComplete','Level complete'):t('GameOver','Game over');overlay.querySelector('.game-over-note').textContent=note;overlay.querySelector('.game-over-tap').textContent=t('TapToContinue','Tap to continue');
  const badge=overlay.querySelector('.game-over-badge');if(badge){const sy=result.lives===level.lives?452:level.endless?324:388,ctx=badge.getContext('2d');if(assets.buttons){ctx.globalCompositeOperation='lighter';ctx.drawImage(assets.buttons,414,sy,58,56,0,0,116,112);}else drawBadge(ctx,sy,116,112);}
  const unlockAt=performance.now()+2000;overlay.onclick=()=>{if(performance.now()>=unlockAt)showMainMenu();};gameOverUnlockTimer=setTimeout(()=>overlay.classList.add('unlocked'),2000);
}
function towerColor(type){return {BLASTER:'#55ff84',LASER:'#29aaff',MISSILE:'#ff4778',SHOCK:'#fff35c',THUMP:'#ff55ed',POP:'#c260ff'}[type]??'#fff';}
$('toggleDesktopPanel').onclick=()=>{const open=$('gameScreen').classList.toggle('desktop-panel-open');$('toggleDesktopPanel').setAttribute('aria-expanded',String(open));$('toggleDesktopPanel').textContent=open?'Hide desktop controls':'Desktop controls';};
$('startWave').onclick=()=>game?.startWave();$('upgradeTower').onclick=()=>game?.upgrade();$('laserLock').onclick=()=>game?.toggleLaserLock();$('linkTower').onclick=()=>game?.beginLink();$('sellTower').onclick=()=>game?.sell();$('pauseGame').onclick=()=>game?.togglePause();$('backToLevels').onclick=()=>{game?.destroy();game=null;$('tutorialOverlay').hidden=true;renderLevels();show($('levelScreen'));};
const persistActiveGame=()=>game?.persist();addEventListener('beforeunload',persistActiveGame);addEventListener('pagehide',persistActiveGame);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')persistActiveGame();});

registerPwa();
initialize();
