const EMPTY=()=>({version:1,scores:{},achievements:[]});
export class ProfileStore{
  constructor(storage,key='swarm-web-profile-v1'){this.storage=storage;this.key=key;this.data=this.load();}
  load(){try{const value=JSON.parse(this.storage?.getItem(this.key));return value?.version===1?value:EMPTY();}catch{return EMPTY();}}
  save(){try{this.storage?.setItem(this.key,JSON.stringify(this.data));}catch{}}
  record(level,result){const key=level.sourceName,old=this.data.scores[key],livesLost=level.lives-result.lives;if(result.won&&(!old||result.score>old.score))this.data.scores[key]={score:result.score,difficulty:level.difficulty,livesLost:old?.livesLost===0?0:livesLost,endless:level.endless,name:level.name};else if(result.won&&old&&old.livesLost!==0&&livesLost===0)old.livesLost=0;const earned=new Set(this.data.achievements),code=level.difficulty[0].toUpperCase(),scores=Object.values(this.data.scores),completed=scores.filter(s=>s.difficulty===level.difficulty).length,perfect=scores.filter(s=>s.difficulty===level.difficulty&&s.livesLost===0).length;if(completed>0)earned.add(code+'1');if(completed>=9)earned.add(code+'2');if(perfect>=9)earned.add(code+'3');if(result.gotX50)earned.add('CC');const upgradeCodes={BLASTER:'LB',LASER:'LL',MISSILE:'LM',SHOCK:'LS',POP:'LV'};for(const type of result.fullyUpgraded??[])if(upgradeCodes[type])earned.add(upgradeCodes[type]);if(result.won&&new Set(result.placedTypes??[]).size===5)earned.add('TH');this.data.achievements=[...earned];this.save();return this.data.scores[key];}
  highScore(level){return this.data.scores[level.sourceName]??null;}
  leaderboard(){return Object.values(this.data.scores).sort((a,b)=>b.score-a.score);}
}
export const ACHIEVEMENTS={E1:'Complete an Easy mission',E2:'Complete nine Easy missions',E3:'Perfect nine Easy missions',M1:'Complete a Medium mission',M2:'Complete nine Medium missions',M3:'Perfect nine Medium missions',H1:'Complete a Hard mission',H2:'Complete nine Hard missions',H3:'Perfect nine Hard missions',CC:'Earn a ×50 close-call bonus',LB:'Fully upgrade a Blaster',LL:'Fully upgrade a Laser',LM:'Fully upgrade a Missile',LS:'Fully upgrade a Shock tower',LV:'Fully upgrade a Vortex',TH:'Win after building all five tower classes'};
