const utf8=new TextDecoder('utf-8'),utf16=new TextDecoder('utf-16le');
function seven(bytes,state){let value=0,shift=0,b;do{if(state.pos>=bytes.length)throw new Error('Truncated resource length.');b=bytes[state.pos++];value|=(b&127)<<shift;shift+=7;}while(b&128);return value;}
export function parseDotNetResources(bytes){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let start=-1;for(let i=0;i<bytes.length-4;i++)if(view.getUint32(i,true)===0xbeefcace){start=i;break;}if(start<0)throw new Error('No managed resource payload found.');const state={pos:start+4},i32=()=>{const value=view.getInt32(state.pos,true);state.pos+=4;return value;};i32();const headerBytes=i32();state.pos+=headerBytes;const version=i32();if(version!==2)throw new Error(`Unsupported managed resource version ${version}.`);const count=i32(),typeCount=i32();for(let i=0;i<typeCount;i++){const length=seven(bytes,state);state.pos+=length;}while((state.pos-start)%8)state.pos++;state.pos+=count*4;const positions=[];for(let i=0;i<count;i++)positions.push(i32());const dataOffset=i32(),namesStart=state.pos,result={};for(const position of positions){state.pos=namesStart+position;const nameBytes=seven(bytes,state),name=utf16.decode(bytes.subarray(state.pos,state.pos+nameBytes));state.pos+=nameBytes;const valueOffset=i32();state.pos=start+dataOffset+valueOffset;const type=seven(bytes,state);if(type===1){const valueBytes=seven(bytes,state);result[name]=utf8.decode(bytes.subarray(state.pos,state.pos+valueBytes));}}return result;}
export async function loadArchiveStrings(archive,language=(globalThis.navigator?.language??'en').slice(0,2).toLowerCase()){
  const english={};for(const entry of ['geoLib.dll','geoDefenseSwarmWP7.dll'])if(archive.has(entry))Object.assign(english,parseDotNetResources(await archive.bytes(entry)));
  if(language==='en')return english;
  const localized={};for(const entry of [`${language}/geoLib.resources.dll`,`${language}/geoDefenseSwarmWP7.resources.dll`])if(archive.has(entry))Object.assign(localized,parseDotNetResources(await archive.bytes(entry)));
  return Object.keys(localized).length?{...english,...localized}:english;
}
